import { Dimensions, StyleSheet } from 'react-native';

const isSmallScreen = Dimensions.get('window').width < 390;

export const estilosHistorial = StyleSheet.create({
    contenedor: {
        flex: 1,
        backgroundColor: '#06101C',
    },
    brilloSuperior: {
        position: 'absolute',
        top: -70,
        right: -50,
        width: 220,
        height: 220,
        borderRadius: 110,
        backgroundColor: 'rgba(0, 255, 156, 0.08)',
    },
    brilloInferior: {
        position: 'absolute',
        bottom: -70,
        left: -60,
        width: 240,
        height: 240,
        borderRadius: 120,
        backgroundColor: 'rgba(127, 179, 255, 0.08)',
    },
    contenido: {
        flexGrow: 1,
        paddingHorizontal: isSmallScreen ? 16 : 20,
        paddingTop: isSmallScreen ? 16 : 20,
        paddingBottom: 28,
    },
    cuerpo: {
        width: '100%',
        maxWidth: 980,
        alignSelf: 'center',
    },
    tarjetaPrincipal: {
        borderRadius: 30,
        padding: isSmallScreen ? 18 : 22,
        marginBottom: 18,
        backgroundColor: 'rgba(10, 19, 35, 0.96)',
        borderWidth: 1,
        borderColor: 'rgba(132, 196, 255, 0.12)',
        shadowColor: '#000',
        shadowOpacity: 0.22,
        shadowRadius: 16,
        shadowOffset: { width: 0, height: 12 },
        elevation: 7,
    },
    etiqueta: {
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'flex-start',
        paddingHorizontal: 12,
        paddingVertical: 7,
        borderRadius: 999,
        backgroundColor: 'rgba(0, 255, 156, 0.10)',
        marginBottom: 14,
    },
    iconoEtiqueta: {
        marginRight: 6,
    },
    textoEtiqueta: {
        color: '#7BFFD1',
        fontSize: 12,
        fontWeight: '800',
        letterSpacing: 0.7,
        textTransform: 'uppercase',
    },
    titulo: {
        color: '#F6F9FF',
        fontSize: isSmallScreen ? 24 : 28,
        fontWeight: '900',
        lineHeight: 34,
        marginBottom: 10,
    },
    subtitulo: {
        color: '#9AA8C4',
        fontSize: isSmallScreen ? 14 : 15,
        lineHeight: 22,
    },
    filaDeEstado: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginTop: 16,
    },
    chip: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 999,
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.08)',
        marginRight: 10,
        marginBottom: 10,
    },
    iconoChip: {
        marginRight: 6,
    },
    textoChip: {
        color: '#DDE7F6',
        fontSize: 12,
        fontWeight: '700',
    },
    tarjetaGrafica: {
        borderRadius: 24,
        padding: isSmallScreen ? 16 : 18,
        marginBottom: 18,
        backgroundColor: 'rgba(10, 19, 35, 0.96)',
        borderWidth: 1,
        borderColor: 'rgba(73, 140, 255, 0.16)',
    },
    tituloGrafica: {
        color: '#EDF4FF',
        fontSize: 16,
        fontWeight: '800',
        marginBottom: 12,
    },
    tarjetaLectura: {
        width: '100%',
        borderRadius: 24,
        padding: 18,
        marginBottom: 14,
        backgroundColor: 'rgba(10, 19, 35, 0.94)',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.08)',
        shadowColor: '#000',
        shadowOpacity: 0.16,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 8 },
        elevation: 5,
    },
    sensores: {
        color: '#00FF9C',
        fontSize: 17,
        fontWeight: '800',
        marginBottom: 4,
    },
    texto: {
        color: '#DDE7F6',
        fontSize: 13,
        marginTop: 5,
    },
    fecha: {
        color: '#9CA3AF',
        marginTop: 10,
        fontSize: 12,
    },
    estadoVacio: {
        color: '#A9B9D3',
        fontSize: 14,
        textAlign: 'center',
        marginTop: 18,
    },
});

export const styles = estilosHistorial;