import { Dimensions, StyleSheet } from 'react-native';

const isSmallScreen = Dimensions.get('window').width < 390;

export const estilosPerfil = StyleSheet.create({
    contenedor: {
        flex: 1,
        backgroundColor: '#06101C',
    },
    brilloSuperior: {
        position: 'absolute',
        top: -70,
        right: -50,
        width: 220,
        height: 220,
        borderRadius: 110,
        backgroundColor: 'rgba(0, 255, 156, 0.08)',
    },
    brilloInferior: {
        position: 'absolute',
        bottom: -70,
        left: -60,
        width: 240,
        height: 240,
        borderRadius: 120,
        backgroundColor: 'rgba(127, 179, 255, 0.08)',
    },
    contenido: {
        flexGrow: 1,
        paddingHorizontal: isSmallScreen ? 16 : 20,
        paddingTop: isSmallScreen ? 16 : 20,
        paddingBottom: 28,
    },
    cuerpo: {
        width: '100%',
        maxWidth: 980,
        alignSelf: 'center',
    },
    tarjetaPrincipal: {
        borderRadius: 30,
        padding: isSmallScreen ? 18 : 22,
        marginBottom: 18,
        backgroundColor: 'rgba(10, 19, 35, 0.96)',
        borderWidth: 1,
        borderColor: 'rgba(132, 196, 255, 0.12)',
        shadowColor: '#000',
        shadowOpacity: 0.22,
        shadowRadius: 16,
        shadowOffset: { width: 0, height: 12 },
        elevation: 7,
    },
    etiqueta: {
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'flex-start',
        paddingHorizontal: 12,
        paddingVertical: 7,
        borderRadius: 999,
        backgroundColor: 'rgba(0, 255, 156, 0.10)',
        marginBottom: 14,
    },
    iconoEtiqueta: {
        marginRight: 6,
    },
    textoEtiqueta: {
        color: '#7BFFD1',
        fontSize: 12,
        fontWeight: '800',
        letterSpacing: 0.7,
        textTransform: 'uppercase',
    },
    titulo: {
        color: '#F6F9FF',
        fontSize: isSmallScreen ? 24 : 28,
        fontWeight: '900',
        lineHeight: 34,
        marginBottom: 10,
    },
    subtitulo: {
        color: '#9AA8C4',
        fontSize: isSmallScreen ? 14 : 15,
        lineHeight: 22,
    },
    tarjetaDatos: {
        borderRadius: 24,
        padding: isSmallScreen ? 16 : 18,
        marginBottom: 18,
        backgroundColor: 'rgba(10, 19, 35, 0.96)',
        borderWidth: 1,
        borderColor: 'rgba(73, 140, 255, 0.16)',
    },
    filaDato: {
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255, 255, 255, 0.06)',
    },
    etiquetaDato: {
        color: '#9AA8C4',
        fontSize: 12,
        fontWeight: '700',
        marginBottom: 4,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    valorDato: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '800',
    },
    botonCerrarSesion: {
        minHeight: 52,
        borderRadius: 16,
        paddingHorizontal: 16,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#00FF9C',
    },
    botonAdministrarUsuarios: {
        minHeight: 52,
        borderRadius: 16,
        paddingHorizontal: 16,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(10, 19, 35, 0.96)',
        borderWidth: 1,
        borderColor: 'rgba(0, 255, 156, 0.32)',
        marginBottom: 12,
    },
    botonAdmin: {
        minHeight: 52,
        borderRadius: 16,
        paddingHorizontal: 16,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(10, 19, 35, 0.96)',
        borderWidth: 1,
        borderColor: 'rgba(127, 179, 255, 0.22)',
        marginBottom: 12,
    },
    iconoBoton: {
        marginRight: 8,
    },
    textoBoton: {
        color: '#06131F',
        fontSize: 15,
        fontWeight: '900',
    },
    textoBotonAdministrar: {
        color: '#7BFFD1',
        fontSize: 15,
        fontWeight: '900',
    },
    textoBotonAdmin: {
        color: '#DDE7F6',
        fontSize: 15,
        fontWeight: '900',
        marginLeft: 8,
    },
    iconoBotonAdministrar: {
        marginRight: 8,
    },
    iconoBotonAdmin: {
        marginRight: 0,
    },
    loadingText: {
        color: '#A9B9D3',
        fontSize: 14,
        textAlign: 'center',
        marginTop: 20,
    },
    estadoVacio: {
        color: '#A9B9D3',
        fontSize: 14,
        textAlign: 'center',
        marginTop: 18,
    },
});

export const styles = estilosPerfil;
