import { Dimensions, StyleSheet } from 'react-native';

const isSmallScreen = Dimensions.get('window').width < 390;

export const estilosAcciones = StyleSheet.create({
    contenedor: {
        flex: 1,
        backgroundColor: '#06101C',
    },
    brilloSuperior: {
        position: 'absolute',
        top: -70,
        right: -50,
        width: 220,
        height: 220,
        borderRadius: 110,
        backgroundColor: 'rgba(0, 255, 156, 0.08)',
    },
    brilloInferior: {
        position: 'absolute',
        bottom: -70,
        left: -60,
        width: 240,
        height: 240,
        borderRadius: 120,
        backgroundColor: 'rgba(127, 179, 255, 0.08)',
    },
    contenido: {
        flexGrow: 1,
        paddingHorizontal: isSmallScreen ? 16 : 20,
        paddingTop: isSmallScreen ? 16 : 20,
        paddingBottom: 28,
    },
    cuerpo: {
        width: '100%',
        maxWidth: 980,
        alignSelf: 'center',
    },
    tarjetaPrincipal: {
        borderRadius: 30,
        padding: isSmallScreen ? 18 : 22,
        marginBottom: 18,
        backgroundColor: 'rgba(10, 19, 35, 0.96)',
        borderWidth: 1,
        borderColor: 'rgba(132, 196, 255, 0.12)',
        shadowColor: '#000',
        shadowOpacity: 0.22,
        shadowRadius: 16,
        shadowOffset: { width: 0, height: 12 },
        elevation: 7,
    },
    etiqueta: {
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'flex-start',
        paddingHorizontal: 12,
        paddingVertical: 7,
        borderRadius: 999,
        backgroundColor: 'rgba(0, 255, 156, 0.10)',
        marginBottom: 14,
    },
    iconoEtiqueta: {
        marginRight: 6,
    },
    textoEtiqueta: {
        color: '#7BFFD1',
        fontSize: 12,
        fontWeight: '800',
        letterSpacing: 0.7,
        textTransform: 'uppercase',
    },
    titulo: {
        color: '#F6F9FF',
        fontSize: isSmallScreen ? 24 : 28,
        fontWeight: '900',
        lineHeight: 34,
        marginBottom: 10,
    },
    subtitulo: {
        color: '#9AA8C4',
        fontSize: isSmallScreen ? 14 : 15,
        lineHeight: 22,
    },
    filaDeEstado: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginTop: 16,
    },
    chip: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 999,
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.08)',
        marginRight: 10,
        marginBottom: 10,
    },
    iconoChip: {
        marginRight: 6,
    },
    textoChip: {
        color: '#DDE7F6',
        fontSize: 12,
        fontWeight: '700',
    },
    tarjetaControl: {
        borderRadius: 24,
        padding: isSmallScreen ? 16 : 18,
        marginBottom: 18,
        backgroundColor: 'rgba(10, 19, 35, 0.96)',
        borderWidth: 1,
        borderColor: 'rgba(73, 140, 255, 0.16)',
    },
    filaBotones: {
        flexDirection: isSmallScreen ? 'column' : 'row',
        marginTop: 14,
    },
    boton: {
        flex: isSmallScreen ? 0 : 1,
        width: isSmallScreen ? '100%' : 'auto',
        minHeight: 52,
        borderRadius: 16,
        paddingHorizontal: 16,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    botonEncender: {
        backgroundColor: '#00FF9C',
        marginRight: isSmallScreen ? 0 : 12,
        marginBottom: isSmallScreen ? 12 : 0,
    },
    botonApagar: {
        backgroundColor: 'rgba(127, 179, 255, 0.16)',
        borderWidth: 1,
        borderColor: 'rgba(127, 179, 255, 0.28)',
        marginTop: isSmallScreen ? 0 : 0,
    },
    iconoBoton: {
        marginRight: 8,
    },
    textoBotonEncender: {
        color: '#06131F',
        fontSize: 15,
        fontWeight: '900',
    },
    textoBotonApagar: {
        color: '#EDF4FF',
        fontSize: 15,
        fontWeight: '900',
    },
    tarjetaLista: {
        borderRadius: 24,
        padding: 18,
        backgroundColor: 'rgba(10, 19, 35, 0.94)',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.08)',
    },
    tarjetaAccion: {
        borderRadius: 18,
        padding: 16,
        marginBottom: 12,
        backgroundColor: 'rgba(255, 255, 255, 0.03)',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.06)',
    },
    tituloAccion: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '800',
        marginBottom: 6,
    },
    texto: {
        color: '#DDE7F6',
        fontSize: 13,
        marginTop: 4,
    },
    estadoVacio: {
        color: '#A9B9D3',
        fontSize: 14,
        textAlign: 'center',
        marginTop: 18,
    },
    loadingText: {
        color: '#A9B9D3',
        fontSize: 14,
        textAlign: 'center',
        marginTop: 20,
    },
    loadingHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 10,
    },
    loadingIcon: {
        marginRight: 8,
    },
    loadingTitle: {
        color: '#F6F9FF',
        fontSize: 16,
        fontWeight: '800',
    },
    emptyStateWrap: {
        alignItems: 'center',
        paddingVertical: 4,
        marginTop: 12,
        marginBottom: 6,
    },
    emptyStateIcon: {
        marginBottom: 10,
    },
    emptyStateTitle: {
        color: '#F6F9FF',
        fontSize: 16,
        fontWeight: '800',
        textAlign: 'center',
        marginBottom: 6,
    },
    emptyStateText: {
        color: '#9AA8C4',
        fontSize: 14,
        lineHeight: 20,
        textAlign: 'center',
    },
});
