import { StyleSheet } from 'react-native';

export const estilosPending = StyleSheet.create({
    contenedor: {
        flex: 1,
        backgroundColor: '#06101C',
    },
    brilloSuperior: {
        position: 'absolute',
        top: -70,
        right: -50,
        width: 220,
        height: 220,
        borderRadius: 110,
        backgroundColor: 'rgba(0, 255, 156, 0.08)',
    },
    brilloInferior: {
        position: 'absolute',
        bottom: -70,
        left: -60,
        width: 240,
        height: 240,
        borderRadius: 120,
        backgroundColor: 'rgba(127, 179, 255, 0.08)',
    },
    contenido: {
        flexGrow: 1,
        paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 28,
    },
    cuerpo: {
        flex: 1,
        width: '100%',
        maxWidth: 980,
        alignSelf: 'center',
        justifyContent: 'center',
    },
    tarjetaPrincipal: {
        borderRadius: 30,
        padding: 22,
        backgroundColor: 'rgba(10, 19, 35, 0.96)',
        borderWidth: 1,
        borderColor: 'rgba(132, 196, 255, 0.12)',
        shadowColor: '#000',
        shadowOpacity: 0.22,
        shadowRadius: 16,
        shadowOffset: { width: 0, height: 12 },
        elevation: 7,
    },
    etiqueta: {
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'flex-start',
        paddingHorizontal: 12,
        paddingVertical: 7,
        borderRadius: 999,
        backgroundColor: 'rgba(255, 193, 7, 0.10)',
        marginBottom: 14,
    },
    iconoEtiqueta: {
        marginRight: 6,
    },
    textoEtiqueta: {
        color: '#FFD76A',
        fontSize: 12,
        fontWeight: '800',
        letterSpacing: 0.7,
        textTransform: 'uppercase',
    },
    titulo: {
        color: '#F6F9FF',
        fontSize: 28,
        fontWeight: '900',
        lineHeight: 34,
        marginBottom: 10,
    },
    subtitulo: {
        color: '#9AA8C4',
        fontSize: 15,
        lineHeight: 22,
    },
    alerta: {
        marginTop: 18,
        borderRadius: 24,
        padding: 18,
        backgroundColor: 'rgba(73, 140, 255, 0.10)',
        borderWidth: 1,
        borderColor: 'rgba(73, 140, 255, 0.16)',
    },
    alertaTitulo: {
        color: '#DCE7F7',
        fontSize: 16,
        fontWeight: '800',
        marginBottom: 6,
    },
    alertaTexto: {
        color: '#A9B9D3',
        fontSize: 14,
        lineHeight: 20,
    },
    botonCerrarSesion: {
        minHeight: 52,
        borderRadius: 16,
        paddingHorizontal: 16,
        marginTop: 18,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#00FF9C',
    },
    iconoBoton: {
        marginRight: 8,
    },
    textoBoton: {
        color: '#06131F',
        fontSize: 15,
        fontWeight: '900',
    },
    nota: {
        color: '#73829B',
        fontSize: 12,
        textAlign: 'center',
        marginTop: 14,
        lineHeight: 18,
    },
});

export const styles = estilosPending;
