import { StyleSheet } from 'react-native';

export const loginStyle = StyleSheet.create({
    contenedor: {
        flex: 1,
        backgroundColor: '#07111E',
        paddingHorizontal: 20,
        justifyContent: 'center',
    },
    keyboardWrapper: {
        flex: 1,
    },
    safeArea: {
        flex: 1,
    },
    screenBody: {
        flexGrow: 1,
        justifyContent: 'center',
        paddingVertical: 20,
    },
    glowTop: {
        position: 'absolute',
        top: -70,
        right: -40,
        width: 220,
        height: 220,
        borderRadius: 110,
        backgroundColor: 'rgba(0, 255, 156, 0.12)',
    },
    glowBottom: {
        position: 'absolute',
        bottom: -80,
        left: -60,
        width: 240,
        height: 240,
        borderRadius: 120,
        backgroundColor: 'rgba(73, 140, 255, 0.12)',
    },
    tarjeta: {
        width: '100%',
        maxWidth: 430,
        alignSelf: 'center',
        paddingVertical: 24,
        paddingHorizontal: 22,
        borderRadius: 30,
        backgroundColor: 'rgba(10, 19, 35, 0.92)',
        borderWidth: 1,
        borderColor: 'rgba(132, 196, 255, 0.16)',
        shadowColor: '#000',
        shadowOpacity: 0.28,
        shadowRadius: 20,
        shadowOffset: { width: 0, height: 14 },
        elevation: 10,
    },
    badge: {
        alignSelf: 'flex-start',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 999,
        backgroundColor: 'rgba(0, 255, 156, 0.12)',
        marginBottom: 16,
    },
    badgeText: {
        color: '#7BFFD1',
        fontSize: 12,
        fontWeight: '700',
        letterSpacing: 0.8,
        textTransform: 'uppercase',
    },
    logo: {
        width: 84,
        height: 84,
        marginBottom: 14,
        alignSelf: 'center',
        resizeMode: 'contain',
    },
    titulo: {
        color: '#F5F8FF',
        fontSize: 24,
        fontWeight: '800',
        textAlign: 'center',
        marginBottom: 8,
    },
    subtitulo: {
        color: '#9AA8C4',
        fontSize: 13,
        textAlign: 'center',
        lineHeight: 20,
        marginBottom: 20,
    },
    texto: {
        color: '#D9E4F4',
        fontSize: 12,
        fontWeight: '600',
        marginBottom: 6,
        marginTop: 4,
    },
    inputL: {
        width: '100%',
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 16,
        backgroundColor: '#0E1B2E',
        color: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#1E3556',
        marginBottom: 14,
    },
    boton: {
        width: '100%',
        minHeight: 48,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#00FF9C',
        marginTop: 8,
    },
    botonSecundario: {
        width: '100%',
        minHeight: 48,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.12)',
        marginTop: 10,
    },
    botonTexto: {
        color: '#06131F',
        fontSize: 14,
        fontWeight: '800',
    },
    botonTextoSecundario: {
        color: '#EDF4FF',
        fontSize: 14,
        fontWeight: '700',
    },
    footerText: {
        color: '#8E9DB7',
        fontSize: 11,
        textAlign: 'center',
        marginTop: 14,
        lineHeight: 16,
    },
});