import { StyleSheet } from 'react-native';

export const registerStyle = StyleSheet.create({
    contenedor: {
        flex: 1,
        backgroundColor: '#07111E',
        paddingHorizontal: 20,
        justifyContent: 'center',
    },
    glowTop: {
        position: 'absolute',
        top: -80,
        left: -50,
        width: 220,
        height: 220,
        borderRadius: 110,
        backgroundColor: 'rgba(73, 140, 255, 0.14)',
    },
    glowBottom: {
        position: 'absolute',
        bottom: -90,
        right: -70,
        width: 250,
        height: 250,
        borderRadius: 125,
        backgroundColor: 'rgba(0, 255, 156, 0.10)',
    },
    tarjeta: {
        width: '100%',
        maxWidth: 430,
        alignSelf: 'center',
        paddingVertical: 28,
        paddingHorizontal: 22,
        borderRadius: 30,
        backgroundColor: 'rgba(10, 19, 35, 0.92)',
        borderWidth: 1,
        borderColor: 'rgba(132, 196, 255, 0.16)',
        shadowColor: '#000',
        shadowOpacity: 0.28,
        shadowRadius: 20,
        shadowOffset: { width: 0, height: 14 },
        elevation: 10,
    },
    badge: {
        alignSelf: 'flex-start',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 999,
        backgroundColor: 'rgba(73, 140, 255, 0.14)',
        marginBottom: 16,
    },
    badgeText: {
        color: '#A8CBFF',
        fontSize: 12,
        fontWeight: '700',
        letterSpacing: 0.8,
        textTransform: 'uppercase',
    },
    logo: {
        width: 92,
        height: 92,
        marginBottom: 18,
        alignSelf: 'center',
        resizeMode: 'contain',
    },
    titulo: {
        color: '#F5F8FF',
        fontSize: 28,
        fontWeight: '800',
        textAlign: 'center',
        marginBottom: 8,
    },
    subtitulo: {
        color: '#9AA8C4',
        fontSize: 15,
        textAlign: 'center',
        lineHeight: 21,
        marginBottom: 24,
    },
    texto: {
        color: '#D9E4F4',
        fontSize: 13,
        fontWeight: '600',
        marginBottom: 8,
        marginTop: 6,
    },
    inputL: {
        width: '100%',
        paddingVertical: 14,
        paddingHorizontal: 16,
        borderRadius: 16,
        backgroundColor: '#0E1B2E',
        color: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#1E3556',
        marginBottom: 14,
    },
    boton: {
        width: '100%',
        minHeight: 52,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#00FF9C',
        marginTop: 10,
    },
    botonSecundario: {
        width: '100%',
        minHeight: 52,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.12)',
        marginTop: 12,
    },
    botonTexto: {
        color: '#06131F',
        fontSize: 15,
        fontWeight: '800',
    },
    botonTextoSecundario: {
        color: '#EDF4FF',
        fontSize: 15,
        fontWeight: '700',
    },
    footerText: {
        color: '#8E9DB7',
        fontSize: 12,
        textAlign: 'center',
        marginTop: 18,
        lineHeight: 18,
    },
});