//importamos el style 
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#e8d6d6',
        paddingHorizontal: 24,
        paddingTop: 60,
        alignItems: 'center',
    },
    title: {
        fontSize: 36,
        fontWeight: '800',
        color: '#ffffff',
        marginBottom: 24,
        textAlign: 'center',
    },
    emailContainer: {
        width: '80%',
        backgroundColor: '#ffffff',
        borderRadius: 12,
        paddingVertical: 12,
        paddingHorizontal: 16,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
        elevation: 3,
    },
    emailText: {
        fontSize: 16,
        color: '#222',
        textAlign: 'center',
        fontWeight: '500',
    },
    resumen: {
        marginTop: 18,
        marginBottom: 12,
        fontSize: 18,
        fontWeight: '700',
        color: '#222',
    },
    resumenCard: {
        width: '80%',
        backgroundColor: '#fff',
        borderRadius: 10,
        padding: 14,
        marginBottom: 10,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    resumenLabel: {
        fontSize: 15,
        color: '#444',
        fontWeight: '600',
    },
    resumenNumber: {
        fontSize: 20,
        fontWeight: '800',
        color: '#444',
    },
    resumenItem: {
        fontSize: 16,
        marginVertical: 8,
        color: '#333',
        fontWeight: '500',
    },
    logoutButton: {
        marginTop: 12,
        alignSelf: 'center',
        backgroundColor: '#8f9aa0',
        paddingVertical: 14,
        paddingHorizontal: 26,
        borderRadius: 14,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.06,
        shadowRadius: 3,
        elevation: 2,
    },
    logoutText: {
        color: '#ffffff',
        fontWeight: '700',
        fontSize: 16,
    },
    logoutTouchable: {
        padding: 10,
    },
});